export const GET_ORDER_REQUEST: 'GET_ORDER_REQUEST' = 'GET_ORDER_REQUEST';
export const GET_ORDER_SUCCESS: 'GET_ORDER_SUCCESS' = 'GET_ORDER_SUCCESS';
export const GET_ORDER_FAILED: 'GET_ORDER_FAILED' = 'GET_ORDER_FAILED';
export const GET_ORDER_NUMBER:'GET_ORDER_NUMBER' = 'GET_ORDER_NUMBER';
export const UPDATE_ORDER: 'UPDATE_ORDER' = 'UPDATE_ORDER';
