export const GET_REGISTER_REQUEST:'GET_REGISTER_REQUEST' = 'GET_REGISTER_REQUEST';
export const GET_REGISTER_SUCCESS:'GET_REGISTER_SUCCESS' = 'GET_REGISTER_SUCCESS';
export const GET_REGISTER_FAILED:'GET_REGISTER_FAILED' = 'GET_REGISTER_FAILED';

export const GET_LOGIN_REQUEST:'GET_LOGIN_REQUEST' = 'GET_LOGIN_REQUEST';
export const GET_LOGIN_SUCCESS:'GET_LOGIN_SUCCESS' = 'GET_LOGIN_SUCCESS';
export const GET_LOGIN_FAILED:'GET_LOGIN_FAILED' = 'GET_LOGIN_FAILED';

export const LOG_OUT_REQUEST:'LOG_OUT_REQUEST' = 'LOG_OUT_REQUEST';
export const LOG_OUT_SUCCESS:'LOG_OUT_SUCCESS' = 'LOG_OUT_SUCCESS';
export const LOG_OUT_FAILED:'LOG_OUT_FAILED' = 'LOG_OUT_FAILED';

export const FORGOT_PASSWORD_REQUEST:'FORGOT_PASSWORD_REQUEST' = 'FORGOT_PASSWORD_REQUEST';
export const FORGOT_PASSWORD_SUCCESS:'FORGOT_PASSWORD_SUCCESS' = 'FORGOT_PASSWORD_SUCCESS';
export const FORGOT_PASSWORD_FAILED:'FORGOT_PASSWORD_FAILED' = 'FORGOT_PASSWORD_FAILED';

export const RESET_PASSWORD_REQUEST:'RESET_PASSWORD_REQUEST' = 'RESET_PASSWORD_REQUEST';
export const RESET_PASSWORD_SUCCESS:'RESET_PASSWORD_SUCCESS' = 'RESET_PASSWORD_SUCCESS';
export const RESET_PASSWORD_FAILED:'RESET_PASSWORD_FAILED' = 'RESET_PASSWORD_FAILED';

export const USER_REQUEST:'USER_REQUEST' = 'USER_REQUEST';
export const USER_SUCCESS:'USER_SUCCESS' = 'USER_SUCCESS';
export const USER_FAILED:'USER_FAILED' = 'USER_FAILED';
export const SET_USER:'SET_USER' = 'SET_USER';
export const GET_USER_REQUEST:'GET_USER_REQUEST' = 'GET_USER_REQUEST';
export const GET_USER_SUCCESS:'GET_USER_SUCCESS' = 'GET_USER_SUCCESS';
export const GET_USER_FAILED:'GET_USER_FAILED' = 'GET_USER_FAILED';